### ISSUE TITLE
KUON Support

### ISSUE THREAD

**Issue by real-guilty** [Shadowth117/Aqua-Toolset#10]
Can extract all.bnd using QuickBMS and chrrox's script, but Aqua (and Yabber) cannot decipher .bnd, .tm2, or .tex files. (On a related note, no tools seem able to open/view these .tm2 files--tried Noesis, TIM2View, and Rainbow--so the script might not be accurately performing the extraction.)

**Comment by Shadowth117** [comment]
If someone goes and adds these to SoulsFormatsNEXT, the branch of SoulsFormats I use since the creator doesn't maintain the original now, someday, maybe it'd be something to look at, but really, right now that sounds like what's probably a lot of unique formats to reverse engineer on a whim.

That All.bnd looks fairly basic, but everything else would be a lot of new territory that frankly I don't feel like tackling out of nowhere. I have other projects I want to do. 

Also, this really doesn't belong on this repo.
