### ISSUE TITLE
Newer version missing "add root node" option

### ISSUE THREAD

**Issue by zosoab70** [Shadowth117/Aqua-Toolset#11]
Hi, Im currently using an older version of aqua tools, i dont know what version it is but its a couple months old. this version has an option box to add a root node when converting a flver with soulsmodeltool. when i updated to the newest version i noticed some options changed and the "add root node" option is missing. without that option the armatures come in missing the first bone (usually spine) and anything weighted to that bone has the weights deleted and in-game the meshes will stretch into the floor. why was this feature removed, or am i missing something?

**Comment by Shadowth117** [comment]
It wasn't functioning as expected and actually ended up being a huge problem for a few things because of how it worked. I saw complaints over it and removed it since it wasn't fulfilling a good purpose. I could see about readding it, but this seems like a Blender specific problem. 

If you really need something for right this moment, you could try exporting to .smd with the latest version. But .smd will not have vertex colors or more than one uv channel. Still, it should be very similar to what bloodborne tool puts out.

**Comment by zosoab70** [comment]
the older version is still working fine so i am good for now. i dunno what the issues it was causing were, but without it the armatures dont import properly into blender.

**Comment by Shadowth117** [comment]
> the older version is still working fine so i am good for now. i dunno what the issues it was causing were, but without it the armatures dont import properly into blender.
> 
> update: fount out the add root node option doesnt work for my friend, but it works for me, so i have no idea whas going on : /

Might be related to the importer you're using. Some people use a different fbx plugin you can find in the blender store or something.

**Comment by Shadowth117** [comment]
Readded as of today's updates
