### ISSUE TITLE
SDK & missing .json issues?

### ISSUE THREAD

**Issue by sthompson216** [Shadowth117/Aqua-Toolset#3]
I keep getting errors like: 
Build started: Project: AquaModelLibrary.Core, Configuration: Debug Any CPU ------
11>C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\[Username]\Downloads\Aqua-Toolset-12_17_2023\PSO2-Aqua-Library\AquaModelLibrary.Core\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
11>Done building project "AquaModelLibrary.Core.csproj" -- FAILED.
12>------ Build started: Project: AquaModelTool, Configuration: Debug Any CPU ------
13>------ Build started: Project: SoulsModelTool, Configuration: Debug Any CPU ------
14>------ Build started: Project: CMXPatcher, Configuration: Debug Any CPU ------
15>------ Build started: Project: AquaAutoRig, Configuration: Debug Any CPU ------
14>C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\[Username]\Downloads\Aqua-Toolset-12_17_2023\CMXPatcher\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
14>Done building project "CMXPatcher.csproj" -- FAILED.
15>C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\[Username]\Downloads\Aqua-Toolset-12_17_2023\AquaAutoRig\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
15>Done building project "AquaAutoRig.csproj" -- FAILED.
13>C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\[Username]\Downloads\Aqua-Toolset-12_17_2023\SoulsModelTool\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
13>Done building project "SoulsModelTool.csproj" -- FAILED.
12>C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'C:\Users\[Username]\Downloads\Aqua-Toolset-12_17_2023\AquaModelTool\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
12>Done building project "AquaModelTool.csproj" -- FAILED.
========== Build: 0 succeeded, 15 failed, 2 up-to-date, 0 skipped ========"

**Comment by Shadowth117** [comment]
Yeah I'm not sure, but it doesn't seem like something related to the project itself. 
Personally, I clone using GitKraken and use it to initialize submodules. 
Perhaps what you used for cloning somehow had problems? One of the answers here suggests a similar experience, though you're welcome to check around.
https://stackoverflow.com/questions/48440223/assets-file-project-assets-json-not-found-run-a-nuget-package-restore/72282034

Either way, given I'm able to clone and build okay after copying in the fbx sdk stuff to the FBX dependencies folder in AquaModelLibrary.Native (Blame Autodesk there), I think it's fine?

I'm going to close this because it sounds a lot more like a general .NET compilation grievance or an issue with my repo here. 
I welcome you to convince me otherwise, but that's really how it looks for now.
