### ISSUE TITLE
Split Soulsmodel tool from Aqua tool or at least update description

### ISSUE THREAD

**Issue by Inokentych** [Shadowth117/Aqua-Toolset#9]
Well it not exactly issue but rather suggestion to put "Souls model tool" separate from main pack or at least mention in description of this utility pack about it have Souls related utility, because for now it super confusing that it is part of some utilities for game not related to souls and even not mention in description about it. just because of this i only recently (few month ago) found out that this utility pack have souls related thing by some random comment in elden ring's texture edit forum topic.

**Comment by Shadowth117** [comment]
I mean like with any tool once you know, you know. 

It being utilities for a game that's not related to souls... is because that's how it began. It got far bigger than I had intended it to because the scene didn't have many great options for model conversion for a long time. All I even added this for was a side project in Demon's Souls I did and somehow that ended up expanding to the other games. 

I went ahead and just wrote up a summary for now in the repo readme, but yeah, that's all that's gonna happen for now.
